/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import com.sun.awt.AWTUtilities;
import database.DBConnect;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    private int x, y;
    private String user = "";
    private String pass = "";
    public Login() {
        initComponents();

        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userTF = new javax.swing.JTextField();
        passTF = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        inicioLbl = new javax.swing.JLabel();
        cancelLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        base = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTF.setBackground(new java.awt.Color(255, 255, 102));
        userTF.setFont(new java.awt.Font("Britannic Bold", 3, 18)); // NOI18N
        userTF.setForeground(new java.awt.Color(255, 153, 51));
        userTF.setBorder(null);
        userTF.setOpaque(false);
        jPanel1.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 250, 40));

        passTF.setBackground(new java.awt.Color(255, 255, 102));
        passTF.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        passTF.setForeground(new java.awt.Color(255, 153, 0));
        passTF.setBorder(null);
        passTF.setOpaque(false);
        jPanel1.add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesde/txt_pass.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 310, 70));

        inicioLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesde/btn_iniciar1.png"))); // NOI18N
        inicioLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicioLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioLblMouseClicked(evt);
            }
        });
        jPanel1.add(inicioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 120, 70));

        cancelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesde/btn_cancelar1.png"))); // NOI18N
        cancelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLblMouseClicked(evt);
            }
        });
        jPanel1.add(cancelLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesde/faq-c2c.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, 110));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 330, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesde/txt_user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 310, 60));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesde/frame.png"))); // NOI18N
        jPanel1.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void inicioLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioLblMouseClicked
        // TODO add your handling code here:
        user = userTF.getText();
        pass = passTF.getText();
        DBConnect db = new DBConnect();
        boolean validPW = db.validateCred(user, pass);
        if (validPW) {
            JFGestionA frm = new JFGestionA();
            frm.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_inicioLblMouseClicked

    private void cancelLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLblMouseClicked
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_cancelLblMouseClicked
    
    public String getUser() {
        return user;
    }
    public String getPass(){
        return pass;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JLabel cancelLbl;
    private javax.swing.JLabel inicioLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
